Add some motivation to the CI job on MacOS
It currently fails with this message:

    Error: Refusing to uninstall /usr/local/Cellar/ruby/3.3.5
    because it is required by asciidoctor, which is currently installed.
    You can override this and force removal with:
      brew uninstall --ignore-dependencies ruby