Disable multibyte encodings tests
They can be caught with a NATFIXME when running a single test, but for
some reason this breaks when running all tests:

  ArgumentError: invalid byte sequence in UTF-8