fix compile issue on x86 MacOS
by ignoring x86_64 Apple devices in the `gc_signal_handler` since
that handler is not used on Apple devices.

This fixes a build issue where compilation fails with a

```
error: member reference type 'struct __darwin_mcontext64 *' is a pointer; did you mean to use '->'?
```

error message.