Bytecode VM: Use fetch instead of [] to get instruction class
This improves the error handling in case of an invalid instruction
(which can happen when you try to run the rb file instead of the
bytecode file. Of course that has never happened to me...)

Old error: undefined method `deserialize' for nil
New error: index 100 outside of array bounds: -96...96